name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Sw3tch
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Brazil/Sao_Paulo
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
